const blackout = document.createElement('div');
blackout.style.position = 'fixed';
blackout.style.top = '0';
blackout.style.left = '0';
blackout.style.width = '100%';
blackout.style.height = '100%';
blackout.style.backgroundColor = 'black';
blackout.style.zIndex = '999999';
blackout.style.pointerEvents = 'none';
blackout.style.opacity = '0.95';
document.body.appendChild(blackout);
